Repository SunbrightCreators/Moiso-Back, pull requests merged in 2025-08, with the labels that each got.

#15 SexChoices, BankCategoryChoices, NotificationCategoryChoices 추가
  utils/choices.py
Labels: feature✨, database🗃️

#25 ZoomChoices 추가, FundingStatusChoices 수정
  utils/choices.py
Labels: feature✨, database🗃️

#29 RewardStatusChoices 추가
  utils/choices.py
Labels: feature✨, database🗃️

#45 require_query_params 데코레이터 추가
  utils/decorators.py
Labels: development🔨, feature✨

#47 버그 해결 및 마이그레이션
  accounts/admin.py
  accounts/migrations/0001_initial.py
  accounts/models.py
  accounts/views.py
  configs/settings/base.py
  configs/urls.py
  fundings/admin.py
  fundings/migrations/0001_initial.py
  fundings/models.py
  fundings/views.py
  notifications/migrations/0001_initial.py
  notifications/views.py
  pays/admin.py
  pays/migrations/0001_initial.py
  pays/models.py
  pays/tests.py
  pays/views.py
  proposals/migrations/0001_initial.py
  proposals/models.py
  proposals/views.py
Labels: bug🐛, database🗃️

#51 accounts API 추가
  accounts/migrations/0002_alter_founder_industry_alter_proposer_industry.py
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
  proposals/migrations/0002_alter_proposal_industry.py
Labels: development🔨, feature✨

#66 Funding 모델 reward_code 필드 null, blank 허용
  fundings/migrations/0003_alter_funding_amount_description_and_more.py
  fundings/models.py
Labels: bug🐛, database🗃️

#59 제안 좋아요 추가/삭제, 제안 스크랩 추가/삭제, 제안 스크랩 목록 조회 API 추가
  proposals/models.py
  proposals/querysets.py
  proposals/serializers.py
  proposals/services.py
  proposals/urls.py
  proposals/views.py
Labels: development🔨, feature✨

#63 펀딩 좋아요 추가/삭제, 펀딩 스크랩 추가/삭제, 펀딩 스크랩 목록 조회 API 추가
  fundings/models.py
  fundings/querysets.py
  fundings/serializers.py
  fundings/services.py
  fundings/urls.py
  fundings/views.py
Labels: development🔨, feature✨

#73 엑세스 토큰 유효기간 1시간으로 상향 조정
  configs/settings/base.py
Labels: refactor♻️, config⚙

#83 GPS 위치기록 추가 구현
  accounts/serializers.py
  accounts/urls.py
  accounts/views.py
Labels: development🔨, feature✨

#75 pays 앱 Order 모델 추가
  fundings/migrations/0006_merge_20250824_1845.py
  pays/admin.py
  pays/migrations/0002_order.py
  pays/models.py
Labels: feature✨, database🗃️

#72 fundings_api 구현+지도탐색수정사항반영+펀딩글상태갱신서비스
  fundings/management/settle_fundings.py
  fundings/migrations/0006_merge_20250824_1640.py
  fundings/migrations/0007_alter_reward_amount.py
  fundings/models.py
  fundings/querysets.py
  fundings/serializers.py
  fundings/services.py
  fundings/urls.py
  fundings/views.py
  utils/helpers.py
Labels: development🔨, feature✨

#81 accounts-레벨구현
  accounts/management/compute_proposer_levels.py
  accounts/services.py
Labels: development🔨, feature✨

#87 최종 마이그레이션
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_founder_industry_alter_proposer_industry.py
  accounts/migrations/0003_alter_founder_business_hours.py
  fundings/migrations/0001_initial.py
  fundings/migrations/0002_alter_funding_business_hours_alter_funding_schedule.py
  fundings/migrations/0003_alter_funding_amount_description_and_more.py
  fundings/migrations/0003_alter_funding_founder_image.py
  fundings/migrations/0003_fix_missing_proposal_column.py
  fundings/migrations/0004_merge_20250821_2334.py
  fundings/migrations/0004_merge_20250822_2218.py
  fundings/migrations/0005_funding_business_name.py
  fundings/migrations/0006_merge_20250824_0238.py
  fundings/migrations/0006_merge_20250824_1640.py
  fundings/migrations/0006_merge_20250824_1845.py
  fundings/migrations/0007_alter_reward_amount.py
  notifications/migrations/0001_initial.py
  pays/migrations/0001_initial.py
  pays/migrations/0002_order.py
  proposals/migrations/0001_initial.py
  proposals/migrations/0002_alter_proposal_industry.py
  proposals/migrations/0003_alter_proposal_business_hours.py
Labels: refactor♻️, database🗃️
